name: action doesn't work???

on:
  push:
    branches:
      - health_check

jobs:
  CI:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    concurrency: deploy-group
        steps:
      - run: echo "works"