name: Health check

on:
  push:
    branches:
      - health_check
  schedule:
    - cron: "15 11,12 * * *"

jobs:
  CI:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-ve7b.onrender.com/health
