name: Health check

on:
  schedule:
    - cron: "15 15,16 * * *"   # <=== Change this value
  push:
    branches:
      -health_check


jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "healt check"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        With:
          url: https://full-stack-open-pokedex-ve7b.onrender.com/health