name: Health check

on:
  # schedule:
  #   - cron: '30 12,11 * * *'
  #   - cron: '40 14 * * *'
  push:
    branches:
      - health_check

jobs:
  health_check:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-ve7b.onrender.com/health

